apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rules
  namespace: {{ .Release.Namespace }}   # or omit and rely on Helmâ€™s -n
data:
  sensitive_files.json: |-
{{ .Files.Get "files/sensitive_files.json" | indent 4 }}
  custom_rules.json: |-
{{ .Files.Get "files/custom_rules.json" | indent 4 }}
  security_rules.json: |-
{{ .Files.Get "files/security_rules.json" | indent 4 }}

