apiVersion: v1
kind: ConfigMap
metadata:
  name: sentrilite-config
  namespace: {{ .Values.namespace }}
data:
  {{- if .Values.integrations.pagerdutyEventsURL }}
  PAGERDUTY_EVENTS_URL: "{{ .Values.integrations.pagerdutyEventsURL }}"
  {{- end }}
  {{- if .Values.integrations.alertmanagerURL }}
  ALERTMANAGER_URL: "{{ .Values.integrations.alertmanagerURL }}"
  {{- end }}

