# charts/sentrilite/templates/secret-license.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.existingSecretName | default "sentrilite-license" }}
  namespace: {{ .Values.namespace | default "kube-system" }}
type: Opaque
data:
  {{ .Values.license.fileKey | default "license.key" }}: {{ .Files.Get "files/license.key" | b64enc }}
