{{- if .Values.integrations.pagerdutyRoutingKey }}
apiVersion: v1
kind: Secret
metadata:
  name: sentrilite-integrations
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  PAGERDUTY_ROUTING_KEY: "{{ .Values.integrations.pagerdutyRoutingKey }}"
{{- end }}

