namespace: kube-system

image:
  repository: docker.io/sentrilite/sentrilite
  tag: "1.0.9"
  pullPolicy: Always

license:
  existingSecretName: sentrilite-license   # Secret with key: license.key
  fileKey: license.key
  mountPath: /opt/sentrilite/license.key   # (kept for reference; container reads this path)

integrations:
  pagerdutyRoutingKey: ""
  pagerdutyEventsURL: ""
  alertmanagerURL: ""

rbac:
  create: true
  name: sentrilite-read

pod:
  labels: {}
  tolerations:
    - operator: Exists
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
  hostPID: true
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
